//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotifySync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotifySync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotifySync.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want unpair {0}?.
        /// </summary>
        public static string AreYouSureUnpair {
            get {
                return ResourceManager.GetString("AreYouSureUnpair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        public static string AutoStart {
            get {
                return ResourceManager.GetString("AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        public static string DeviceNameLabel {
            get {
                return ResourceManager.GetString("DeviceNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device isn&apos;t connected.
        /// </summary>
        public static string DeviceNotConnected {
            get {
                return ResourceManager.GetString("DeviceNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss notifications on remote device by click.
        /// </summary>
        public static string DismissNotificationsByClick {
            get {
                return ResourceManager.GetString("DismissNotificationsByClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable end-to-end encryption (recommended).
        /// </summary>
        public static string EnableEncryption {
            get {
                return ResourceManager.GetString("EnableEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File received from {0}.
        /// </summary>
        public static string FileReceivedFrom {
            get {
                return ResourceManager.GetString("FileReceivedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File successfully sent to {0}.
        /// </summary>
        public static string FileSentTo {
            get {
                return ResourceManager.GetString("FileSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find device.
        /// </summary>
        public static string FindDevice {
            get {
                return ResourceManager.GetString("FindDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General settings.
        /// </summary>
        public static string GeneralSettingsButton {
            get {
                return ResourceManager.GetString("GeneralSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming call.
        /// </summary>
        public static string IncomingCall {
            get {
                return ResourceManager.GetString("IncomingCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device successfully paired.
        /// </summary>
        public static string NewDeviceNotification {
            get {
                return ResourceManager.GetString("NewDeviceNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No paired devices.
        /// </summary>
        public static string NoDevices {
            get {
                return ResourceManager.GetString("NoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications to display.
        /// </summary>
        public static string NoNotifications {
            get {
                return ResourceManager.GetString("NoNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair new device.
        /// </summary>
        public static string PairNewDeviceButton {
            get {
                return ResourceManager.GetString("PairNewDeviceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving file from {0}.
        /// </summary>
        public static string ReceivingFileFrom {
            get {
                return ResourceManager.GetString("ReceivingFileFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan this QR code on your device in NotifySync app to pair devices.
        /// </summary>
        public static string ScanQRCodeLabel {
            get {
                return ResourceManager.GetString("ScanQRCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send file....
        /// </summary>
        public static string SendFile {
            get {
                return ResourceManager.GetString("SendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending file to {0}....
        /// </summary>
        public static string SendingFileTo {
            get {
                return ResourceManager.GetString("SendingFileTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share clipboard.
        /// </summary>
        public static string ShareClipboard {
            get {
                return ResourceManager.GetString("ShareClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in folder.
        /// </summary>
        public static string ShowInFolder {
            get {
                return ResourceManager.GetString("ShowInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon TrayIcon {
            get {
                object obj = ResourceManager.GetObject("TrayIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send file ({0}).
        /// </summary>
        public static string UnableToSendFile {
            get {
                return ResourceManager.GetString("UnableToSendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpair.
        /// </summary>
        public static string UnpairDeviceButton {
            get {
                return ResourceManager.GetString("UnpairDeviceButton", resourceCulture);
            }
        }
    }
}
